spring:
  application:
    name: notification-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/notifications
  datasource:
    url: jdbc:mysql://localhost:3306/logs
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

server:
  port: 9090

consumers:
  allowed-origins: http://localhost:5173